### ISSUE TITLE
Download v.0.2 corrupt?

### ISSUE THREAD

**Issue by casio** [stubbornella/oocss#1]
Hi,

something about the download v.0.2 seems broken - when trying to get the file, I get:

<pre>
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>19B455775F1B6DFE</RequestId><HostId>kEfk+0wLB52fAlw4ypVYhoSpaHZTC9a5k4iUHrq46iomVQLzV4rYmw4cnt+6fnCx</HostId></Error>
</pre>

Github bug?!

Cheers,
carsten

**Comment by thomasd** [comment]
Got the same error just 1 minute (07.May.2009 15:28) ago!

**Comment by jvandyke** [comment]
Same problem here.  0.1 works fine.

**Comment by jvandyke** [comment]
Keep in mind that the download button in the project header above does work and is linked to the newest version.

**Comment by stubbornella** [comment]
ok, the zip should be fixed now. Not sure if it was a github issue or a me issue, but I just deleted it and uploaded the same file again. Let me know if you still have issues.

**Comment by stubbornella** [comment]
closing the issue

**Comment by casio** [comment]
No, download working fine now. Thanks!

**Comment by f2elinks** [comment]
No issues now!Thanks!
