### ISSUE TITLE
CSS Reset or Normalize?

### ISSUE THREAD

**Issue by iDGS** [stubbornella/oocss#100]
Just recently, I downloaded stubbornella-oocss-6e481bc for study. When looking over the media.html page, I of course cut in the media_debug.css addition referenced back in the core.css file, to see what was what.  And what happened then was the media page layout got messed up.  So, looking things over, I decided, kind of on a whim, to just replace then entire content of the libraries.css file with the content of http://necolas.github.com/normalize.css/   I then, doing a little back-and-forth editing, looked at the same media page in four separate browser tabs, viewing (Normal v. Debug) using the reset in libraries.css, compared to (Normal v. Debug) using the normalize.css alternative.  And guess what?  Problems went away!  True, the page did look a little different under normalize.  Nicer, I'd say.  Check it out, why not?  I was pretty impressed!  Maybe you'll like it too. :-)

**Comment by scottromack** [comment]
Normalize!

**Comment by stubbornella** [comment]
I'm moving the project over to normalize right now. ;)

**Comment by scottromack** [comment]
Normalize fixes things I didn't know were broken and leaves alone things that aren't.
