### ISSUE TITLE
with the module class can you put a module inside of a module?

### ISSUE THREAD

**Issue by lifeiscontent** [stubbornella/oocss#104]
Hi there, I've noticed that a lot of things inside of the designers comps I'm working with could be considered a module...

however, when I started to code the site I begun to overwrite module properties because the things I was inheriting didn't follow the design.

I assume you wouldn't put a module inside of a module... but in the facebook design there are modules inside of modules... unless these stacked items should be called something else.

please advise.

Thanks!

**Comment by KyNorthstar** [comment]
Was there ever an actual answer to this?

**Comment by lifeiscontent** [comment]
@BenLeggiero it was 8 years ago, I’m having trouble remembering what my intent was. But no, never got answered.
