### ISSUE TITLE
Use position absolute on .tl and .tr? (migrated from lighthouse)

### ISSUE THREAD

**Issue by jonherman** [stubbornella/oocss#14]
Reported by cfenzo | May 13th, 2009 @ 12:41 AM

Case: With the current float based solution, any content (text, image) in .inner/.bd/.hd will gain a right/left indent from the floated .tl and .tr. This will limit the flexibility of the module content in such way that the space (padding) between the border and the content can never be smaller than the width of .tl and .tr.

The problem seems to be non-existent for .bl and .br.

Suggested solution: Adding position absolute and top/right/left values for .tl and .tr will prevent this, while still working as expected (as far as I can confirm, testing in IE (6,7,8), Opera (9.6), Firefox (3.0.1), and Safari (4.0 beta win)).

**Comment by stubbornella** [comment]
Fixed via negative margin.
