### ISSUE TITLE
pop on IE6 don't show

### ISSUE THREAD

**Issue by Zerzio** [stubbornella/oocss#15]
The pop example provided in the Velocity package doesn't show correctly on IE6.
I did some experiment myself without success.

**Comment by stubbornella** [comment]
did you try the gc module?

**Comment by levito** [comment]
The upper right corner image is not aligned correctly in IE6. My fix in mod.css mod.css, replacing the last rule:
.pop .tr{float:right;margin-right:-10px;_display:inline;/_fix double margin bug_/}

**Comment by stubbornella** [comment]
weird, that shouldn't work because float and inline are incompatible. Float automatically puts an elem in display block.

**Comment by levito** [comment]
Weird? It's a tried and tested fix for the IE5/6 double margin bug which occurs when both float and margin are added to left or right. See here: http://www.positioniseverything.net/explorer/doubled-margin.html

**Comment by gaspas** [comment]
if you give text-align: right to .top that fix.
I do not see any other implications in the use of this .Top

I change on mod.css line 21
.top{background-position:center top; text-align:right}

**Comment by stubbornella** [comment]
@levito - thanks, I put your fix in. Commit dabb9e0
