### ISSUE TITLE
User wants to modify the port in their dev environment

### ISSUE THREAD

**Issue by stubbornella** [stubbornella/oocss#161]
Right now the port is set to 8080, some users may not have localhost:8080 available, they should be able to set the port for the vagrant install

**Comment by pflannery** [comment]
go to the /vagrantfile and open it in a notepad

where it says:
  # === box config ===
  config.vm.network :forwarded_port, guest: 80, host: 8080

change the 8080 to a different port of your liking (note: you must keep guest: 80 as that it what is being forwarded from the vm) 

This example is for http://localhost:7878 from our browser
  # === box config ===
  config.vm.network :forwarded_port, guest: 80, host: 7878

hope that helps ;)

oh and don't forget to restart you vagrant instance

**Comment by stubbornella** [comment]
@arnogues - Can you document this please in the readme?
