### ISSUE TITLE
Opera and grids

### ISSUE THREAD

**Issue by ibrezac** [stubbornella/oocss#20]
Hi,

Grids do not appear to be working in Opera 10.x.  It looks like display: table-cell does not work as expected.  I have not been to come up with a work around.

Any ideas?

Thanks,
-igor

**Comment by levito** [comment]
try adding overflow:hidden to .lastUnit:after - this worked for me.

**Comment by stubbornella** [comment]
ah ha. I had an older version of opera, which is perhaps why I wasn't seeing exactly the same display issues other people mentioned. Upgrading and fixing.

**Comment by stubbornella** [comment]
awesome, this fix totally worked. Very odd, but I'm pleased, since the overflow is only applied to generated content, it should not break anything. I hope. :) Pushed change 085dfa81daacbab8594362d1b59e1dd71e959cb8

**Comment by majic3** [comment]
For me & in opera 10.10 on XP I get .main extending way beyond the page (I sent a screen sot of this to the google group)

However if I use content: "." in grids & template stylesheets everything seems fine

**Comment by Golodhros** [comment]
Hi there!

The fix didnt work for me. It seems that display:table-cell doesn't work in the template either, so I have had to add display:block instead, and a fixed with to my containers.

Great work, by the way!

**Comment by levito** [comment]
Yes, this fix was not the right solution. Don's set display:block - there are reasons for using display:table-cell. Have a look at my comment here: http://github.com/stubbornella/oocss/issues#issue/22/comment/119128
Replace the ". . " by "x x " and it will work again for recent Opera versions. You might want to use my fork - it also includes flexible forms and buttons.

**Comment by Golodhros** [comment]
Perfect! It works pretty smart.

Thanks
