### ISSUE TITLE
Tabs: List Items Hidden in Content

### ISSUE THREAD

**Issue by braddunbar** [stubbornella/oocss#21]
List items within the `.bd` element of the tabs mod are hidden along with the content list item.  For instance, the innermost list item in the following example should be visible but is not:

```
<div class="mod tabs simple">
  <b class="top">...</b>
  <div class="inner">
    <div class="hd topper">...</div>
    <div class="bd">
      <ul>
        <li class="current">
          <p>Lorem Ipsum...</p>
          <ul><li>Should Not Be Hidden</li></ul>
        </li>
      </ul>
    </div>
  </div>
  <b class="bottom">...</b>
</div>
```

In my code I have fixed this with the following declaration:

```
.tabs .bd li li{ display:block; }
```

The content list item is still hidden (unless `.current` is applied) and all descendants are shown by default.

**Comment by martinklepsch** [comment]
```
.tabs .bd li{display:none;}  
.tabs .bd li.current{display:block;}  
```

[tabs.css; L 7,8](http://github.com/stubbornella/oocss/blob/master/css/tabs.css)  
The problem is that all list items within the      <code>.bd</code> div are hidden.  
A better way would be:   

```
 .tabs .bd>ul>li{display:none;}  
 .tabs .bd>ul>li.current{display:block;}    
```

So only the list items directly within the first <code><ul></code> (the tab container) are hidden, unless they have <code>.current</code> applied.    

I didnt tested this...  
When it works for you it would be great if you could fork & patch this.   

Thanks.

**Comment by braddunbar** [comment]
Child selectors would definitely be better, but they won't work in IE7.  I will submit a patch sometime today for this.

**Comment by braddunbar** [comment]
Just submitted a pull request with a patch for this issue.

**Comment by stubbornella** [comment]
Martin, did we get this patch in?

**Comment by martinklepsch** [comment]
I don't think so.  
Will you do it or should I?

**Comment by stubbornella** [comment]
Can you do it? I'm doing better with git, but I don't want to push my luck. ;)

**Comment by martinklepsch** [comment]
okay i picked it up...

**Comment by stubbornella** [comment]
ugh, I lost this change on the latest version. Mklappstuhl is adding it again.

**Comment by martinklepsch** [comment]
got it in again. :)

**Comment by martinklepsch** [comment]
it's there again.
