### ISSUE TITLE
Problem with "Main Content" column in the template in IE7

### ISSUE THREAD

**Issue by lumi77** [stubbornella/oocss#23]
If you open template.html in IE7 you will notice that the Foot block flows inbetween Left Column and Right Column starts right at the bottom of Main Content.
If you set background color (other than white) on Main Content you will see that it spans the whole width of the page.

**Comment by levito** [comment]
I've committed a fix: http://github.com/levito/oocss/commit/0dd8c3edff9b3e44140eb2b9344d0cd52a58fdd0

**Comment by martinklepsch** [comment]
integrated levitos fix.
