### ISSUE TITLE
Tab items display one under another rather than next to each other in IE7

### ISSUE THREAD

**Issue by lumi77** [stubbornella/oocss#24]
table-cell and table-row display styles are used in various style rules in OOCSS. IE6 and IE7 do not honor those display styles. Thus they use default display styles. Surprisingly IE6 displays the tabs as expected. However, IE7 behaves differently. The tab items are treated as block elements and thus displayed vertically.

To reproduce - simply open tabs.html in IE7. Also the controls are displayed vertically.

**Comment by tanila** [comment]
I have the same Problem with IE8 and IE8 in IE7-compat mode :(

**Comment by tanila** [comment]
Have a fix for this: simliy replaced underscore to star-hack to force inline for all IEs:

http://github.com/tanila/oocss/commit/dc774a611db0696df14ef4697b35fd67ed414662

hth
tanila

**Comment by stubbornella** [comment]
I like this, Martin, can you pull it in?

**Comment by sams** [comment]
tanila fix is in master.

Issue is not evident in ie7 - fixed.

**Comment by sams** [comment]
tanila fix is in master.

Issue is not evident in ie7 - fixed.

**Comment by stubbornella** [comment]
Verified
