### ISSUE TITLE
template.html displays incorrectly in Safari 3.2 on Windows

### ISSUE THREAD

**Issue by lumi77** [stubbornella/oocss#25]
Head is displayed between Body and Foot.

Changing display style of "body" class from "table-cell" to "block" fixes this. What is the reason for setting style of body to "table-cell"?

**Comment by levito** [comment]
I also don't see the point of display:table-cell for .body. So I changed it to block and did some cleanup. http://github.com/levito/oocss/commit/847afbe7bb79724e0134c46e435937da1b893312

**Comment by martinklepsch** [comment]
integratec levitos fix.

**Comment by stubbornella** [comment]
we need display table cell on the body to create a new formatting context, clear floats inside and avoid wrapping floats outside
