### ISSUE TITLE
OOCSS:  media object to handle longer text similar to a clolumn, and not wrap below the image.

### ISSUE THREAD

**Issue by screwlewse** [stubbornella/oocss#30]
First, thanks for all your work!  

So with the media block.. I dont think it's working as I would expect.   I would expect the media block to be similar to columns, having a column for the image, and on the other side, text.  However the media block behaves the same as just floating the image left or right..   text flows **below** the image and not staying to the left or right of the image.   

I have read an article that accomplished this, but I dont remember how much hackery was used.  

I have uploaded a test version of what I am talking about.. feel free to check it out.  

http://screwlewse.com/labs/stubbornella-oocss-8b59c19/media_test.html

**Comment by stubbornella** [comment]
Media block requires mod.css. This should be in the documentation. Media is a weird block... half container / half content
