### ISSUE TITLE
Write CSS for OO tabs (migrated from lighthouse)

### ISSUE THREAD

**Issue by jonherman** [stubbornella/oocss#4]
Reported by nicole (at stubbornella) | March 7th, 2009 @ 12:42 AM

Set up the CSS for OO tabs. They need to:

Have a base tab class which extends mod.
Have a hd which contains the tabs
Have a class which extends hd to place the tabs to the right or left (bottom too?)
Consider a class which allows the tabs to live inside or outside the contour.

**Comment by martinklepsch** [comment]
is this already included with the tabs plugin or am i wrong?

**Comment by stubbornella** [comment]
yes, closing
