### ISSUE TITLE
Improvement to clearfix

### ISSUE THREAD

**Issue by aglemann** [stubbornella/oocss#49]
Wondering if the line:

content:" x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x "

Can be re-written as:

content: "\0020"

As used in HTML5 Boilerplate and elsewhere.

**Comment by aglemann** [comment]
Nevermind... this was explained in the Google Group

**Comment by neonstalwart** [comment]
can you link to the post?

**Comment by aglemann** [comment]
http://groups.google.com/group/object-oriented-css/browse_thread/thread/5077f316d38fb7be?hl=en
