### ISSUE TITLE
[root]->index.html->library.html

### ISSUE THREAD

**Issue by phpwalter** [stubbornella/oocss#51]
I just DLed the new OO CSS structure. (Very nice!)

But there seems to be a file missing. The main INDEX page and a link in the upper left corner: "Basic library example"

It's looking for an HTML file that does not exist.

Any ideas?

**Comment by martinklepsch** [comment]
I now deleted this section since library.html doesn't exist anymore... 
It got deleted in 8fb02751bf5bbcffdea94343a8417c9104f73d44 since there was nothing really useful in it.
