### ISSUE TITLE
wordpress twentyten and oocss templates

### ISSUE THREAD

**Issue by cmerot** [stubbornella/oocss#55]
Hi, 
i'm extending the "twentyten" theme for wordpress and am using oocss.
I've just figured out why my page "about" was broken. It's because it's a page, and twentyten adds a "page" class to it's pages :

```
<div id="post-2" class="post-2 page type-page hentry">
```

i've fixed that by adding a prefix to oocss' "page" class.

**Comment by stubbornella** [comment]
There is a bug open to add a prefix to oocss: https://github.com/stubbornella/oocss/issuesearch?state=open&q=prefix#issue/17

**Comment by cmerot** [comment]
ok then, that bug request would fit my needs. I'd also prefer a simple 'oo-' prefix rather than more complex internal namespaces.
