### ISSUE TITLE
Template Example

### ISSUE THREAD

**Issue by gmclelland** [stubbornella/oocss#58]
I am enjoying learning this framework, but I'm confused why in the template examples at http://oocss.org/velocity/exercise3.html do you not use grids as the main skeleton of the page?  Instead you use a div.main and div.leftCol?  I notice this here as well http://waltschmidt.com/v2/.

Also, why do you add negative margins(-3px) on the div.leftCol and div.rightCol?

Thanks for any help you can provide.

**Comment by stubbornella** [comment]
I use columns instead of grids so the middle column can be flexible.

The negative margins are to correct a 3px float bug in IE (more info on position is everything). 

You should join the OOCSS google group.

Cheers,
Nicole

**Comment by gmclelland** [comment]
Are columns nestable?

**Comment by stubbornella** [comment]
No (might work, I've never found a use case), but you can have more than one leftCol or rightCol.
