### ISSUE TITLE
Question from a newbie - valid css

### ISSUE THREAD

**Issue by Catfelix** [stubbornella/oocss#59]
Hi Nicole

I'm just started using CSS and every telling me to validate my code.
How come that this CSS (OOCSS) doesn't validate on W3C website.

Am I missing something?

Catfelix

**Comment by SeanJA** [comment]
It doesn't validate because there are hacks in there to accommodate Internet Explorer, and other browsers.

`_hack` `*hack` `-browser-specific-style`

**Comment by Catfelix** [comment]
Is it good or bad. I mean how can i then use it? Is it better with another CSS framework. and can you recomment something.
My website must validate on W3C

**Comment by sams** [comment]
I feel that at times with web development you find that you need to 'do the wrong thing for the right reasons';  by this I mean the resulting achievements outweight the pitfalls.
When you know why you bending  the rules do so, but for good not bad.

Many use the validator to spot mistakes that they did not intend to make, whilst they ignore the flags to hacks that they have used

BTW the Google group has a discussion on this (see comments by Brad, Nicole & Erik)
http://groups.google.com/group/object-oriented-css/browse_thread/thread/7785d259cbe0c4ac/55cdf5e995bf0756?lnk=gst&q=css+hacks#55cdf5e995bf0756

the web has debates on this point and many argue good and bad for various approaches

**Comment by SeanJA** [comment]
If you are doing a school project, you might not want to use a webframework as it takes most of the learning out of the equation (which you may or may not be dinged for...).

It is better for you to learn about css (and the various hacks that you must use to fix cross browser problems) on your own first before graduating to a framework.

**Comment by Catfelix** [comment]
Hi
No im not in a school project. It just that i've been struggling with css for a long time and have decided that now it is time for learning it the right way. laying the foundation for a proper solution which i can use on my upcomming projects. 
In the past i have been using css, as many developers do, starting from scratch every time. Building and copying from other projects, and my css just getting bigger and bigger.
There must be a better way. 

Then i came across OOCSS and this forum. And i can see the point of reusing objects.
But how to start if i just want to use my own framework?
I allso came across 960.gs and wow this look very nice and easy to use.

But a solid foundation - could it be OOCSS combined with 960.gs or is there a better way?

**Comment by sams** [comment]
This is an issue list **not a forum** the forum link below is where you should post questions
http://groups.google.com/group/object-oriented-css/
