### ISSUE TITLE
Module .bd,.hd,.ft width 100% problem

### ISSUE THREAD

**Issue by DarkSmith** [stubbornella/oocss#60]
The mod.css specify a 100% width for the .hd, .bd and .ft classes. Now it's impossible to add an horizontal padding to a custom heading,body or footer module (the padding width will  overflow the dimensions of the module)

**Comment by stubbornella** [comment]
ah, ok, we'll need to find another way to create a new formatting context and clear floats. Did you have a proposed solution?

**Comment by stubbornella** [comment]
We'll also need another way to keep margins from collapsing between the elements of the module.

**Comment by SeanJA** [comment]
I set .hd, .bd, and .ft to 97% width and added 5px of padding so they wouldn't overlap or butt up against the sides... perhaps that would help?

**Comment by DarkSmith** [comment]
Back in june 2010 the css declaration was like this :

.hd,.bd,.ft{overflow:hidden;_overflow:visible; _zoom:1;}

And I never encounter the issue

**Comment by stubbornella** [comment]
we need both a new formatting context and a clearfix for the body. In the media block, it should stay next to siblings, for the module head, body, and foot, they should stack one above the other. Not quite sure how to accomplish this yet.

**Comment by stubbornella** [comment]
@DarkSmith - that is probably the best way to do it now, as long as you aren't generating popovers or hover menus from inside the module.

@SeanJA - that solution sounds pretty specific to your website.
